/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;
import model.TipoUsuario;

/**
 *
 * @author Ariel
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private TipoUsuario tipoUsuario = null;
    
    private PanelOrganismo unPanelEmpresa;
    private PanelPersona unPanelPersona;
    private PanelEmpleado unPanelEmpleado;
    private PanelUsuario unPanelUsuario;
    private PanelProcesarTurno01 unPanelProcesarTurno01;
    private PanelProcesarTramite01 unPanelProcesarTramite01;

    /**
     * captura la seleccion en el arbol
     */
    String captura = null;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        //Carga Icono de la empresa
        try {
            //Icono de la aplicacion
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());

        } catch (Exception e) {
        }
        initComponents();
        this.setSize(1200, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_TipoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_puesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1330, 850));
        setMinimumSize(new java.awt.Dimension(1330, 850));
        setPreferredSize(new java.awt.Dimension(1330, 850));
        setResizable(false);

        jPanelArbol.setBackground(new java.awt.Color(255, 153, 51));
        jPanelArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);
        jScrollPaneArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("El Porvenir");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administración General");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Organismo");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestión de Turnos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Asignar Turno");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Reasignar Turno");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestion de Tramite");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Procesar Tramite");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver cantidad de Tramites por Area");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver cantidad deTipo de tramite por Area");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setMinimumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(330, 750));
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });
        jScrollPaneArbol.setViewportView(arbolModulos);

        javax.swing.GroupLayout jPanelArbolLayout = new javax.swing.GroupLayout(jPanelArbol);
        jPanelArbol.setLayout(jPanelArbolLayout);
        jPanelArbolLayout.setHorizontalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArbolLayout.setVerticalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelContenido.setBackground(new java.awt.Color(153, 255, 204));
        jPanelContenido.setAlignmentX(0.0F);
        jPanelContenido.setAlignmentY(0.0F);
        jPanelContenido.setAutoscrolls(true);
        jPanelContenido.setMaximumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setMinimumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setName(""); // NOI18N
        jPanelContenido.setPreferredSize(new java.awt.Dimension(950, 750));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(1342, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USUARIO:");

        jlbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO USUARIO");

        jlbl_TipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TIPO EMPLEADO");

        jlbl_puesto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlbl_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl_puesto, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked

        if (arbolModulos.isEnabled()) {
            TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
            if (tp != null) {
                captura = arbolModulos.getSelectionPath().toString();
                /*Intentanmos validar si la cadena equivale a vacio.
                Si ejecutamos nos daremos cuenta que esto
                genera una excepciòn ya que la cadena es nula*/

                if (captura.equals("[El Porvenir, Administración General, Organismo]")) {
                    
                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelEmpresa = new PanelOrganismo();
                    this.unPanelEmpresa.setSize(950, 750);
                    this.unPanelEmpresa.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpresa);
                    this.unPanelEmpresa.validate();

                }

                if (captura.equals("[El Porvenir, Administración General, Personas]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelPersona = new PanelPersona();
                    this.unPanelPersona.setSize(950, 750);
                    this.unPanelPersona.setVisible(true);

                    this.jPanelContenido.add(this.unPanelPersona);
                    
                    this.unPanelPersona.validate();
                }
                if (captura.equals("[El Porvenir, Administración General, Empleados]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Empleado
                    this.unPanelEmpleado = new PanelEmpleado();
                    this.unPanelEmpleado.setSize(950, 750);
                    this.unPanelEmpleado.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpleado);
                    
                    this.unPanelEmpleado.validate();
                }

                if (captura.equals("[El Porvenir, Administración General, Usuarios]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelUsuario = new PanelUsuario();
                    this.unPanelUsuario.setSize(950, 750);
                    this.unPanelUsuario.setVisible(true);

                    this.jPanelContenido.add(this.unPanelUsuario);
                    
                    this.unPanelUsuario.validate();
                }

                if (captura.equals("[El Porvenir, Gestión de Turnos, Asignar Turno]")) {

                    habilitarArbol(false);
                    
                    //Se crea el Panel Emplesa
                    this.unPanelProcesarTurno01 = new PanelProcesarTurno01();
                    this.unPanelProcesarTurno01.setSize(950, 750);
                    this.unPanelProcesarTurno01.setVisible(true);

                    this.jPanelContenido.add(this.unPanelProcesarTurno01);
                    
                    this.unPanelProcesarTurno01.validate();
                }
                
                if (captura.equals("[El Porvenir, Gestion de Tramite, Procesar Tramite]")) {

                    habilitarArbol(false);
                    
                    //Se crea el Panel Emplesa
                    this.unPanelProcesarTramite01 = new PanelProcesarTramite01();
                    this.unPanelProcesarTramite01.setSize(950, 750);
                    this.unPanelProcesarTramite01.setVisible(true);

                    this.jPanelContenido.add(this.unPanelProcesarTramite01);
                    
                    this.unPanelProcesarTramite01.validate();
                }

            }
        }
    }//GEN-LAST:event_arbolModulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTree arbolModulos = new javax.swing.JTree();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JPanel jPanelArbol = new javax.swing.JPanel();
    public static final javax.swing.JPanel jPanelContenido = new javax.swing.JPanel();
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JLabel jlbl_TipoUsuario;
    private javax.swing.JLabel jlbl_puesto;
    private javax.swing.JLabel jlbl_usuario;
    // End of variables declaration//GEN-END:variables

    public void arranca() {
        this.tipoUsuario = LoginController.getInstanceUsuario().getTipoUsuario();

        if (this.tipoUsuario != null) {
            if (this.tipoUsuario.getDescripcion().equals("Persona")) {
                JOptionPane.showMessageDialog(this, "Los Cliente solo pueden ingresar por la web");
                System.exit(0);
            }

            if (this.tipoUsuario.getDescripcion().equals("Empleado")) {
                //Si el usuario posee un empleado asociado
                if (LoginController.getInstanceUsuario().getUnEmpleado() != null) {

                    //Uso del Singleton creado en el Login
                    this.jlbl_usuario.setText(LoginController.getInstanceUsuario().getNombre());
                    this.jlbl_TipoUsuario.setText(LoginController.getInstanceUsuario().getTipoUsuario().getDescripcion());
                    this.jlbl_puesto.setText(LoginController.getInstanceUsuario().getUnEmpleado().getUnTipoEmpleado().getDescripcion());

                    jPanelContenido.repaint();
                    setLocationRelativeTo(null);// centra la ventana en la pantalla
                    setVisible(true);// visualiza la ventana
                    //default title and icon
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario es de tipo empleado, pero no tiene empleado asociado. Contacte con el Administrador");
                    System.exit(0);
                }
            }
        }
    }

    /**
     * Se llama desde cualquier lugar de la aplicación y bloqueara o habilitara
     * el arbol
     *
     * @param estado
     */
    private void habilitarArbol(boolean estado) {
        this.arbolModulos.setEnabled(estado);
        this.jPanelArbol.setEnabled(estado);
        this.jPanelArbol.repaint();
        this.jPanelArbol.validate();

        this.jPanelContenido.removeAll();
        this.jPanelContenido.repaint();
        this.jPanelContenido.validate();
        
        this.repaint();
        this.validate();
    }
    public static javax.swing.JPanel getjPanelArbol() {
        return jPanelArbol;
    }

    public static javax.swing.JPanel getjPanelContenido() {
        return jPanelContenido;
    }

    public static javax.swing.JTree getArbolModulos() {
        return arbolModulos;
    }

}
