/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.ProcesarTurnoController;
import java.awt.Color;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Area;
import model.Empleado;
import model.HorarioAtencionTurno;
import model.TipoAtencion;
import model.TipoTramite;

/**
 *
 * @author Ariel
 */
public class PanelProcesarTurno06 extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;

    private final ProcesarTurnoController controlador;

    /**
     * Creates new form PanelEmpresa
     *
     * @param controlador
     */
    public PanelProcesarTurno06(ProcesarTurnoController controlador) {

        initComponents();
        validador = new ValidadorDeCampos();
        habilitarTodosLosBotones(true);
        this.controlador = controlador;

        this.jpb_estado_procesarTurno.setValue(75);
        this.jpb_estado_procesarTurno.setForeground(new Color(220, 118, 51));

        this.jlbl_titulo.setBackground(new Color(30, 132, 73));
        this.jlbl_titulo.setOpaque(true);

        //Evitar edicion manual de fecha
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jdc_fechaDeTurno.getDateEditor();
        editor.setEditable(false);

        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.RED, Color.WHITE, null, null);
        jdc_fechaDeTurno.setVisible(true);

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_paso = new javax.swing.JLabel();
        jlbl_titulo = new javax.swing.JLabel();
        jpb_estado_procesarTurno = new javax.swing.JProgressBar();
        jPanel_Contenido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_horarioAtencion = new javax.swing.JComboBox<>();
        jdc_fechaDeTurno = new com.toedter.calendar.JDateChooser();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jlbl_paso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_paso.setText("TIPO ATENCIÓN");

        jlbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_titulo.setText("PROCESAR TURNO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("FECHA ATENCIÓN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("HORARIO ATENCIÓN");

        jdc_fechaDeTurno.setDoubleBuffered(false);
        jdc_fechaDeTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdc_fechaDeTurnoMouseClicked(evt);
            }
        });
        jdc_fechaDeTurno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdc_fechaDeTurnoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContenidoLayout = new javax.swing.GroupLayout(jPanel_Contenido);
        jPanel_Contenido.setLayout(jPanel_ContenidoLayout);
        jPanel_ContenidoLayout.setHorizontalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jdc_fechaDeTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jcb_horarioAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel_ContenidoLayout.setVerticalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jdc_fechaDeTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_horarioAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        //Mi JDateChooser es llamado JD_Fecha

        jbtn_siguiente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_siguiente.setText("SIGUIENTE");
        jbtn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_siguienteActionPerformed(evt);
            }
        });

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_paso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpb_estado_procesarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpb_estado_procesarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_paso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel_Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlbl_paso.getAccessibleContext().setAccessibleName("PASO 1");
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();

        //Habilita el Arbol de seleccion
        JFramePrincipal.getArbolModulos().setEnabled(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().repaint();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jbtn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_siguienteActionPerformed
        HorarioAtencionTurno nuevaHoraAtencion = (HorarioAtencionTurno) this.jcb_horarioAtencion.getSelectedItem();
        
        this.controlador.getNuevoTurno().setUnaHoraTurno(nuevaHoraAtencion);
        this.controlador.getNuevoTurno().setFecha(jdc_fechaDeTurno.getDate());

        //Se crea el Panel Emplesa    
        PanelProcesarTurno07 unPaneProcesarTurno07 = new PanelProcesarTurno07(this.controlador);
        unPaneProcesarTurno07.setSize(950, 750);
        unPaneProcesarTurno07.setLocation(0, 0);
        unPaneProcesarTurno07.setVisible(true);

        //JFramePrincipal.modificarPanelContenido(unPanelProcesarTurno02);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().add(unPaneProcesarTurno07);
        JFramePrincipal.getjPanelContenido().repaint();
        JFramePrincipal.getjPanelContenido().validate();

    }//GEN-LAST:event_jbtn_siguienteActionPerformed

    private void jdc_fechaDeTurnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdc_fechaDeTurnoPropertyChange
        Date date;
        date = jdc_fechaDeTurno.getDate();

        if (date != null) {
            this.jcb_horarioAtencion.removeAllItems();
            this.validate();

            if (validador.calcularFechaTurno(date)) {
                this.validador.habilitarBoton(true, this.jbtn_siguiente, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCombobox(true, jcb_horarioAtencion);

                cargarHorarios();

            } else {
                JOptionPane.showConfirmDialog(this, "              La fecha ingresada es invalida \n"
                        + "tiene que ser una fecha igual o superior al dia de hoy \n"
                        + "             modifique la fecha por favor", "Aceptar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);

                this.jdc_fechaDeTurno.setCalendar(null);

            }

        } else {
            this.jcb_horarioAtencion.removeAllItems();
            this.validador.habilitarBoton(false, this.jbtn_siguiente, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCombobox(false, jcb_horarioAtencion);
            this.validate();
        }

    }//GEN-LAST:event_jdc_fechaDeTurnoPropertyChange

    private void jdc_fechaDeTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdc_fechaDeTurnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jdc_fechaDeTurnoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_Contenido;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_siguiente;
    private javax.swing.JComboBox<String> jcb_horarioAtencion;
    private com.toedter.calendar.JDateChooser jdc_fechaDeTurno;
    private javax.swing.JLabel jlbl_paso;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JProgressBar jpb_estado_procesarTurno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        //inhabilita campos
        this.validador.habilitarCombobox(estado, jcb_horarioAtencion);
    }

    @Override
    public void limpiarTodosLosCampos() {
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(estado, this.jbtn_siguiente, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    /**
     * Carga las Areas el el JComboBox area
     */
    public void cargarHorarios() {
        DefaultComboBoxModel mdl = new DefaultComboBoxModel(this.controlador.buscarHorariosDeTurnoDisponibles());
        this.jcb_horarioAtencion.setModel(mdl);
    }
}
