/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import dao.exceptions.NonexistentEntityException;
import java.awt.Color;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Usuario;
import view.resources.TablaUsuarioModelListener;
import view.resources.TablaUsuarioModelo;

/**
 *
 * @author Ariel
 */
public class PanelUsuario extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;

    //variables de tabla
    private final TablaUsuarioModelo tablaUsuarioModelo;

    private final UsuarioController controlador;
    private Usuario usuarioSeleccionado;

    private final List<Usuario> usuarios;

    private String crud;

    /**
     * Creates new form PanelPersona
     */
    public PanelUsuario() {
        //JTable vacio
        this.tablaUsuarioModelo = new TablaUsuarioModelo();
        this.validador = new ValidadorDeCampos();

        this.crud = "";

        this.usuarios = new ArrayList<>();
        initComponents();
        habilitarTodosLosBotones(false);
        this.validador.habilitarBoton(true, this.jbtn_volver, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);

        habilitarTodosLosCampos(false);

        //iniciar el controlador de esta vista
        this.controlador = new UsuarioController();
        setSize(800, 600);

        //agrega escuchadores de las tablas
        this.jtb_usuario.getSelectionModel().addListSelectionListener(new TablaUsuarioModelListener(this));

        limpiarTodosLosCampos();

        this.validador.LimitarCaracteres(this.jtf_nickname, 30);
        this.validador.LimitarCaracteres(this.jtf_buscarUsuario, 30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_crud = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jtb_usuario = new javax.swing.JTable();
        jbtn_listar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jtf_buscarUsuario = new javax.swing.JTextField();
        jTabbedPaneContenedor = new javax.swing.JTabbedPane();
        jPanel_datos = new javax.swing.JPanel();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_nickname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_aceptar = new javax.swing.JButton();
        jlbl_mensaje = new javax.swing.JLabel();
        jlbl_alertaConfirmarPassword = new javax.swing.JLabel();
        jlbl_alertaNickName = new javax.swing.JLabel();
        jlbl_alertaPassword = new javax.swing.JLabel();
        jlbl_alertaPersonaAsociada = new javax.swing.JLabel();
        jtf_personaAsociada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_empleadoAsociado = new javax.swing.JTextField();
        jpf_confirmarPassword = new javax.swing.JPasswordField();
        jpf_password = new javax.swing.JPasswordField();
        jlbl_alertaEmpleadoAsociado = new javax.swing.JLabel();
        jPanelPersonaAsociada = new javax.swing.JPanel();
        jScrollPanePersonaAsociada = new javax.swing.JScrollPane();
        jtb_personaAsociada = new javax.swing.JTable();
        jbtn_listarPersona = new javax.swing.JButton();
        jbtn_asignarPersona = new javax.swing.JButton();
        jbtn_volverADatosDeUsuarioPersona = new javax.swing.JButton();
        jbtn_desasignarPersona = new javax.swing.JButton();
        jtf_buscarPersona = new javax.swing.JTextField();
        jPanelEmpleadoAsociado = new javax.swing.JPanel();
        jScrollPaneEmpleadoAsociado = new javax.swing.JScrollPane();
        jtb_empleadoAsociado = new javax.swing.JTable();
        jbtn_listarEmpleado = new javax.swing.JButton();
        jtf_buscarEmpleado = new javax.swing.JTextField();
        jbtn_asignarEmpleado = new javax.swing.JButton();
        jbtn_desasignarEmpleado = new javax.swing.JButton();
        jbtn_volverADatosDeUsuarioEmpleado = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel_crud.setLayout(null);

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        jtb_usuario.setModel(tablaUsuarioModelo);
        jScrollPaneTabla.setViewportView(jtb_usuario);

        jPanel_crud.add(jScrollPaneTabla);
        jScrollPaneTabla.setBounds(10, 10, 700, 160);

        jbtn_listar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listar.setText("LISTAR");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });
        jPanel_crud.add(jbtn_listar);
        jbtn_listar.setBounds(10, 180, 100, 30);

        jbtn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_agregar.setText("AGREGAR");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });
        jPanel_crud.add(jbtn_agregar);
        jbtn_agregar.setBounds(610, 180, 100, 30);

        jtf_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_buscarUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_buscarUsuarioFocusGained(evt);
            }
        });
        jtf_buscarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarUsuarioKeyReleased(evt);
            }
        });
        jPanel_crud.add(jtf_buscarUsuario);
        jtf_buscarUsuario.setBounds(120, 180, 480, 30);

        add(jPanel_crud);
        jPanel_crud.setBounds(70, 40, 720, 220);

        jPanel_datos.setLayout(null);

        jbtn_eliminar.setText("ELIMINAR");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });
        jPanel_datos.add(jbtn_eliminar);
        jbtn_eliminar.setBounds(500, 290, 100, 30);

        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });
        jPanel_datos.add(jbtn_cancelar);
        jbtn_cancelar.setBounds(250, 290, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NICKNAME");
        jPanel_datos.add(jLabel1);
        jLabel1.setBounds(120, 10, 200, 30);

        jtf_nickname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_datos.add(jtf_nickname);
        jtf_nickname.setBounds(340, 10, 260, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel_datos.add(jLabel2);
        jLabel2.setBounds(120, 50, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DNI PERSONA ASOCIADA");
        jPanel_datos.add(jLabel3);
        jLabel3.setBounds(120, 130, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CONFIRMAR PASSWORD");
        jPanel_datos.add(jLabel4);
        jLabel4.setBounds(120, 90, 200, 30);

        jbtn_modificar.setText("MODIFICAR");
        jbtn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modificarActionPerformed(evt);
            }
        });
        jPanel_datos.add(jbtn_modificar);
        jbtn_modificar.setBounds(380, 290, 100, 30);

        jbtn_aceptar.setText("ACEPTAR");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        jPanel_datos.add(jbtn_aceptar);
        jbtn_aceptar.setBounds(120, 290, 100, 30);

        jlbl_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_mensaje.setForeground(new java.awt.Color(255, 0, 0));
        jPanel_datos.add(jlbl_mensaje);
        jlbl_mensaje.setBounds(120, 230, 480, 30);

        jlbl_alertaConfirmarPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_datos.add(jlbl_alertaConfirmarPassword);
        jlbl_alertaConfirmarPassword.setBounds(620, 90, 40, 30);

        jlbl_alertaNickName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_datos.add(jlbl_alertaNickName);
        jlbl_alertaNickName.setBounds(620, 10, 40, 30);

        jlbl_alertaPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_datos.add(jlbl_alertaPassword);
        jlbl_alertaPassword.setBounds(620, 50, 40, 30);

        jlbl_alertaPersonaAsociada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_datos.add(jlbl_alertaPersonaAsociada);
        jlbl_alertaPersonaAsociada.setBounds(620, 130, 40, 30);

        jtf_personaAsociada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_personaAsociada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtf_personaAsociadaMousePressed(evt);
            }
        });
        jPanel_datos.add(jtf_personaAsociada);
        jtf_personaAsociada.setBounds(340, 130, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DNI EMPLEADO ASOCIADO");
        jPanel_datos.add(jLabel5);
        jLabel5.setBounds(120, 170, 200, 30);

        jtf_empleadoAsociado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_empleadoAsociado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtf_empleadoAsociadoMousePressed(evt);
            }
        });
        jPanel_datos.add(jtf_empleadoAsociado);
        jtf_empleadoAsociado.setBounds(340, 170, 260, 30);
        jPanel_datos.add(jpf_confirmarPassword);
        jpf_confirmarPassword.setBounds(340, 90, 260, 30);
        jPanel_datos.add(jpf_password);
        jpf_password.setBounds(340, 50, 260, 30);

        jlbl_alertaEmpleadoAsociado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_datos.add(jlbl_alertaEmpleadoAsociado);
        jlbl_alertaEmpleadoAsociado.setBounds(620, 170, 40, 30);

        jTabbedPaneContenedor.addTab("Datos de Usuario", jPanel_datos);

        jPanelPersonaAsociada.setLayout(null);

        jtb_personaAsociada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePersonaAsociada.setViewportView(jtb_personaAsociada);

        jPanelPersonaAsociada.add(jScrollPanePersonaAsociada);
        jScrollPanePersonaAsociada.setBounds(10, 10, 690, 190);

        jbtn_listarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listarPersona.setText("LISTAR");
        jPanelPersonaAsociada.add(jbtn_listarPersona);
        jbtn_listarPersona.setBounds(10, 220, 100, 30);

        jbtn_asignarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_asignarPersona.setText("ASIGNAR");
        jPanelPersonaAsociada.add(jbtn_asignarPersona);
        jbtn_asignarPersona.setBounds(450, 220, 120, 30);

        jbtn_volverADatosDeUsuarioPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_volverADatosDeUsuarioPersona.setText("VOLVER A DATOS DE USUARIO");
        jPanelPersonaAsociada.add(jbtn_volverADatosDeUsuarioPersona);
        jbtn_volverADatosDeUsuarioPersona.setBounds(10, 290, 690, 30);

        jbtn_desasignarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_desasignarPersona.setText("DESASIGNAR");
        jPanelPersonaAsociada.add(jbtn_desasignarPersona);
        jbtn_desasignarPersona.setBounds(580, 220, 120, 30);
        jPanelPersonaAsociada.add(jtf_buscarPersona);
        jtf_buscarPersona.setBounds(120, 220, 310, 30);

        jTabbedPaneContenedor.addTab("Persona Asociada", jPanelPersonaAsociada);

        jPanelEmpleadoAsociado.setLayout(null);

        jtb_empleadoAsociado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneEmpleadoAsociado.setViewportView(jtb_empleadoAsociado);

        jPanelEmpleadoAsociado.add(jScrollPaneEmpleadoAsociado);
        jScrollPaneEmpleadoAsociado.setBounds(10, 10, 690, 190);

        jbtn_listarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listarEmpleado.setText("LISTAR");
        jPanelEmpleadoAsociado.add(jbtn_listarEmpleado);
        jbtn_listarEmpleado.setBounds(10, 220, 100, 30);
        jPanelEmpleadoAsociado.add(jtf_buscarEmpleado);
        jtf_buscarEmpleado.setBounds(120, 220, 310, 30);

        jbtn_asignarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_asignarEmpleado.setText("ASIGNAR");
        jPanelEmpleadoAsociado.add(jbtn_asignarEmpleado);
        jbtn_asignarEmpleado.setBounds(450, 220, 120, 30);

        jbtn_desasignarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_desasignarEmpleado.setText("DESASIGNAR");
        jPanelEmpleadoAsociado.add(jbtn_desasignarEmpleado);
        jbtn_desasignarEmpleado.setBounds(580, 220, 120, 30);

        jbtn_volverADatosDeUsuarioEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_volverADatosDeUsuarioEmpleado.setText("VOLVER A DATOS DE USUARIO");
        jPanelEmpleadoAsociado.add(jbtn_volverADatosDeUsuarioEmpleado);
        jbtn_volverADatosDeUsuarioEmpleado.setBounds(10, 290, 690, 30);

        jTabbedPaneContenedor.addTab("Empleado Asociado", jPanelEmpleadoAsociado);

        add(jTabbedPaneContenedor);
        jTabbedPaneContenedor.setBounds(70, 270, 720, 370);

        jbtn_volver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_volver.setText("VOLVER");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });
        add(jbtn_volver);
        jbtn_volver.setBounds(70, 653, 720, 60);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla el boton volver
     *
     * @param evt
     */
    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();

        //Habilita el Arbol de seleccion
        JFramePrincipal.habilitarArbol(true);
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * Controla el boton cancelar
     *
     * @param evt
     */
    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        //Actualizar el TableModel con la lista del controlador
        this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

        //Refrescar el modelo en la tabla
        this.tablaUsuarioModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

        this.usuarioSeleccionado = null;

        this.jtb_usuario.setEnabled(true);

        this.jlbl_alertaNickName.setIcon(null);
        this.jlbl_alertaPassword.setIcon(null);
        this.jlbl_alertaConfirmarPassword.setIcon(null);
        this.jlbl_alertaPersonaAsociada.setIcon(null);
        this.jlbl_alertaEmpleadoAsociado.setIcon(null);

        this.jlbl_mensaje.setText("");
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    /**
     * Controla el boton modificar
     *
     * @param evt
     */
    private void jbtn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modificarActionPerformed
        this.crud = "modificar";
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarUsuario);

        this.jtb_usuario.setEnabled(false);


    }//GEN-LAST:event_jbtn_modificarActionPerformed

    /**
     * Controla el boton aceptar si se presiono el boton agregar, llama a la
     * función agregar si se presiono el boton modificar, llama a la función
     * modificar si se presiono el boton eliminar, llama a la función eliminar
     *
     * @param evt
     */
    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        int opcion = 0;
        if (crud.equals("agregar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Agregar la persona", "Confirmar Creación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {
                agregar();
            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                //Refrescar el modelo en la tabla
                this.tablaUsuarioModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                this.usuarioSeleccionado = null;

                this.jtb_usuario.setEnabled(true);

                this.jlbl_alertaNickName.setIcon(null);
                this.jlbl_alertaPassword.setIcon(null);
                this.jlbl_alertaConfirmarPassword.setIcon(null);
                this.jlbl_alertaPersonaAsociada.setIcon(null);
                this.jlbl_alertaEmpleadoAsociado.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }

        if (crud.equals("modificar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Modificar la persona", "Confirmar Modificación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {
                try {
                    modificar();
                } catch (Exception ex) {
                    Logger.getLogger(PanelUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                //Refrescar el modelo en la tabla
                this.tablaUsuarioModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                this.usuarioSeleccionado = null;

                this.jtb_usuario.setEnabled(true);

                this.jlbl_alertaNickName.setIcon(null);
                this.jlbl_alertaPassword.setIcon(null);
                this.jlbl_alertaConfirmarPassword.setIcon(null);
                this.jlbl_alertaPersonaAsociada.setIcon(null);
                this.jlbl_alertaEmpleadoAsociado.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }
        if (crud.equals("eliminar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar la persona", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {

                try {
                    controlador.eliminarUsuario(usuarioSeleccionado);
                    opcion = JOptionPane.showConfirmDialog(null, "La eliminación se realizo con exito", "Persona Eliminada", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE);
                    //Actualizar el TableModel con la lista del controlador
                    this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                    //Refrescar el modelo en la tabla
                    this.tablaUsuarioModelo.fireTableDataChanged();

                    limpiarTodosLosCampos();
                    habilitarTodosLosCampos(false);
                    habilitarTodosLosBotones(false);

                    this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                    this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                    this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                    this.usuarioSeleccionado = null;

                    this.jtb_usuario.setEnabled(true);

                    this.jlbl_alertaNickName.setIcon(null);
                    this.jlbl_alertaPassword.setIcon(null);
                    this.jlbl_alertaConfirmarPassword.setIcon(null);
                    this.jlbl_alertaPersonaAsociada.setIcon(null);
                    this.jlbl_alertaEmpleadoAsociado.setIcon(null);

                    this.jlbl_mensaje.setText("");

                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(PanelUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                //Refrescar el modelo en la tabla
                this.tablaUsuarioModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                this.usuarioSeleccionado = null;

                this.jtb_usuario.setEnabled(true);

                this.jlbl_alertaNickName.setIcon(null);
                this.jlbl_alertaPassword.setIcon(null);
                this.jlbl_alertaConfirmarPassword.setIcon(null);
                this.jlbl_alertaPersonaAsociada.setIcon(null);
                this.jlbl_alertaEmpleadoAsociado.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }


    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    /**
     * Controla el boton Listar
     *
     * @param evt
     */
    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        //Actualizar el TableModel con la lista del controlador
        this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

        //Refrescar el modelo en la tabla
        this.tablaUsuarioModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

        this.usuarioSeleccionado = null;

    }//GEN-LAST:event_jbtn_listarActionPerformed

    /**
     * Controla el boton agregar
     *
     * @param evt
     */
    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        this.crud = "agregar";
        this.validador.limpiarCampo(this.jtf_nickname);
        this.validador.limpiarCampo(this.jtf_empleadoAsociado);
        this.validador.limpiarCampo(this.jtf_personaAsociada);
        this.validador.limpiarCampo(this.jtf_buscarUsuario);
        this.jpf_password.setText("");
        this.jpf_confirmarPassword.setText("");

        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.jtf_empleadoAsociado.setEnabled(false);
        this.jtf_personaAsociada.setEnabled(false);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarUsuario);

        this.jtb_usuario.setEnabled(false);

    }//GEN-LAST:event_jbtn_agregarActionPerformed

    /**
     * Controla el Foco del JTextFiel buscar persona
     *
     * @param evt
     */
    private void jtf_buscarUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_buscarUsuarioFocusGained
        if (this.jtf_buscarUsuario.isEditable()) {
            this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

            //Refrescar el modelo en la tabla
            this.tablaUsuarioModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

            this.usuarioSeleccionado = null;

            this.jtb_usuario.setEnabled(true);

            this.jlbl_alertaNickName.setIcon(null);
            this.jlbl_alertaPassword.setIcon(null);
            this.jlbl_alertaConfirmarPassword.setIcon(null);
            this.jlbl_alertaPersonaAsociada.setIcon(null);
            this.jlbl_alertaEmpleadoAsociado.setIcon(null);

            this.jlbl_mensaje.setText("");
        }
    }//GEN-LAST:event_jtf_buscarUsuarioFocusGained

    /**
     * Escucha si en el JTextFiel buscar persona se presionan teclas
     *
     * @param evt
     */
    private void jtf_buscarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarUsuarioKeyReleased
        if (this.jtf_buscarUsuario.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarUsuariosPorNickName(this.jtf_buscarUsuario.getText()));

            //Refrescar el modelo en la tabla
            this.tablaUsuarioModelo.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtf_buscarUsuarioKeyReleased

    /**
     * Controla el boton eliminar
     *
     * @param evt
     */
    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        this.crud = "eliminar";
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(false);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarUsuario);

        this.jtb_usuario.setEnabled(false);
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jtf_personaAsociadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_personaAsociadaMousePressed
        System.out.println("hola");

        this.jTabbedPaneContenedor.setSelectedIndex(1);
    }//GEN-LAST:event_jtf_personaAsociadaMousePressed

    private void jtf_empleadoAsociadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_empleadoAsociadoMousePressed
        System.out.println("hola");

        this.jTabbedPaneContenedor.setSelectedIndex(2);
    }//GEN-LAST:event_jtf_empleadoAsociadoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelEmpleadoAsociado;
    private javax.swing.JPanel jPanelPersonaAsociada;
    private javax.swing.JPanel jPanel_crud;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JScrollPane jScrollPaneEmpleadoAsociado;
    private javax.swing.JScrollPane jScrollPanePersonaAsociada;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTabbedPane jTabbedPaneContenedor;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_asignarEmpleado;
    private javax.swing.JButton jbtn_asignarPersona;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_desasignarEmpleado;
    private javax.swing.JButton jbtn_desasignarPersona;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JButton jbtn_listarEmpleado;
    private javax.swing.JButton jbtn_listarPersona;
    private javax.swing.JButton jbtn_modificar;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JButton jbtn_volverADatosDeUsuarioEmpleado;
    private javax.swing.JButton jbtn_volverADatosDeUsuarioPersona;
    private javax.swing.JLabel jlbl_alertaConfirmarPassword;
    private javax.swing.JLabel jlbl_alertaEmpleadoAsociado;
    private javax.swing.JLabel jlbl_alertaNickName;
    private javax.swing.JLabel jlbl_alertaPassword;
    private javax.swing.JLabel jlbl_alertaPersonaAsociada;
    private javax.swing.JLabel jlbl_mensaje;
    private javax.swing.JPasswordField jpf_confirmarPassword;
    private javax.swing.JPasswordField jpf_password;
    private javax.swing.JTable jtb_empleadoAsociado;
    private javax.swing.JTable jtb_personaAsociada;
    private javax.swing.JTable jtb_usuario;
    private javax.swing.JTextField jtf_buscarEmpleado;
    private javax.swing.JTextField jtf_buscarPersona;
    private javax.swing.JTextField jtf_buscarUsuario;
    private javax.swing.JTextField jtf_empleadoAsociado;
    private javax.swing.JTextField jtf_nickname;
    private javax.swing.JTextField jtf_personaAsociada;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    //--------------------------Metodos Implementados---------------------------
    //--------------------------------------------------------------------------
    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        this.validador.habilitarCampo(estado, this.jtf_nickname);
        this.validador.habilitarCampo(estado, this.jtf_empleadoAsociado);
        this.validador.habilitarCampo(estado, this.jtf_personaAsociada);
        this.validador.habilitarCampo(estado, this.jtf_buscarUsuario);
        this.jpf_password.setEnabled(estado);
        this.jpf_confirmarPassword.setEnabled(estado);
    }

    @Override
    public void limpiarTodosLosCampos() {
        this.validador.limpiarCampo(this.jtf_nickname);
        this.validador.limpiarCampo(this.jtf_empleadoAsociado);
        this.validador.limpiarCampo(this.jtf_personaAsociada);
        this.validador.limpiarCampo(this.jtf_buscarUsuario);
        this.jpf_password.setText("");
        this.jpf_confirmarPassword.setText("");
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_cancelar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_eliminar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_modificar, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos Getters y Settes------------------------
    //--------------------------------------------------------------------------
    public javax.swing.JButton getJbtn_aceptar() {
        return this.jbtn_aceptar;
    }

    public javax.swing.JButton getJbtn_agregar() {
        return this.jbtn_agregar;
    }

    public javax.swing.JButton getJbtn_cancelar() {
        return this.jbtn_cancelar;
    }

    public javax.swing.JButton getJbtn_eliminar() {
        return this.jbtn_eliminar;
    }

    public javax.swing.JButton getJbtn_modificar() {
        return this.jbtn_modificar;
    }

    public ValidadorDeCampos getValidador() {
        return this.validador;
    }

    public javax.swing.JTextField getJtf_buscarPersona() {
        return this.jtf_buscarUsuario;
    }

    public Usuario getUsuarioSeleccionado() {
        return this.usuarioSeleccionado;
    }

    public void setUsuarioSeleccionado(Usuario usuarioSeleccionado) {
        this.usuarioSeleccionado = usuarioSeleccionado;
    }

    private javax.swing.JPasswordField getJpf_confirmarPassword() {
        return jpf_confirmarPassword;
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos Adicionales-----------------------------
    //--------------------------------------------------------------------------
    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Persona
     */
    public void seleccionarUsuario() {
        limpiarTodosLosCampos();
        //obtiene el indice de la fila seleccionada en la tabla de usuarios
        int filaSeleccionada = this.jtb_usuario.getSelectedRow();
        // si la fila esta seleccionada, seteamos la persona auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.usuarioSeleccionado = this.tablaUsuarioModelo.obtenerUsuarioEn(filaSeleccionada);
            this.jtf_nickname.setText(this.usuarioSeleccionado.getNombre());

            if (usuarioSeleccionado.getUnaPersona() != null) {
                this.jtf_personaAsociada.setText(this.usuarioSeleccionado.getUnaPersona().getDni());
            }
            if (usuarioSeleccionado.getUnEmpleado() != null) {
                this.jtf_empleadoAsociado.setText(this.usuarioSeleccionado.getUnEmpleado().getDni());
            }

            if (usuarioSeleccionado.getClave() != null) {
                this.jpf_password.setText(this.usuarioSeleccionado.getClave());
                this.jpf_confirmarPassword.setText(this.usuarioSeleccionado.getClave());
            }

        } else {
            this.validador.habilitarBoton(false, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_eliminar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_modificar, new Color(30, 132, 73), Color.WHITE, null, null);
        }
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos CRUD------------------------------------
    //--------------------------------------------------------------------------
    /**
     * Crea un persona auxiliar y se lo envia al controlador para que persista
     * si el dni ya existe solicita que se ingrese uno diferente
     */
    public void agregar() {
        String mensaje = "";
        Usuario nuevoUsuario = null;
        String password1 = String.valueOf(jpf_password.getPassword());
        String password2 = String.valueOf(jpf_confirmarPassword.getPassword());

        mensaje = "Completar:";
        if ((!this.jtf_nickname.getText().isEmpty()) && !password1.isEmpty() && !password2.isEmpty() && password1.equals(password2)) {

            nuevoUsuario = new Usuario();
            nuevoUsuario.setNombre(this.jtf_nickname.getText());
            nuevoUsuario.setClave(password1);
            this.jlbl_alertaNickName.setIcon(null);
            this.jlbl_alertaPassword.setIcon(null);
            this.jlbl_alertaConfirmarPassword.setIcon(null);
            this.jlbl_alertaPersonaAsociada.setIcon(null);
            this.jlbl_alertaEmpleadoAsociado.setIcon(null);
            this.jlbl_mensaje.setText("");

        } else {
            if (this.jtf_nickname.getText().isEmpty()) {
                this.jlbl_alertaNickName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Nombre ";
            } else {
                this.jlbl_alertaNickName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (password1.isEmpty()) {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *password vacio ";
            } else {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (password2.isEmpty()) {
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Confirmación de password vacio ";
            } else {
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (password1.equals(password2) && !password1.isEmpty() && !password2.isEmpty()) {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            } else {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
            }
            this.jlbl_mensaje.setText(mensaje);
        }
        if (nuevoUsuario != null) {
            if (this.controlador.agregarUsuario(nuevoUsuario)) {
                this.jlbl_mensaje.setText("");

                //limpiar campos
                //Actualizar el TableModel con la lista del controlador
                this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                //Refrescar el modelo en la tabla
                this.tablaUsuarioModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                this.jtb_usuario.setEnabled(true);

                this.usuarioSeleccionado = null;

                this.jtb_usuario.getSelectionModel().setSelectionInterval(this.tablaUsuarioModelo.getRowCount() - 1, this.tablaUsuarioModelo.getRowCount() - 1);
                this.tablaUsuarioModelo.getValueAt(this.tablaUsuarioModelo.getRowCount() - 1, 0);

                seleccionarUsuario();

                int selectedRow = jtb_usuario.getSelectedRow();
                Rectangle rect = jtb_usuario.getCellRect(selectedRow, 0, true);
                jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
                crud = "";
            } else {
                this.jlbl_alertaNickName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *El USUARIO ya existe, ingrese uno valido";
                this.jlbl_mensaje.setText(mensaje);
            }
        }

    }

    /**
     * Modifica una persona existente
     *
     * @throws java.lang.Exception
     */
    public void modificar() throws Exception {
        String mensaje = "";
        Usuario nuevoUsuario = null;
        mensaje = "Completar:";

        nuevoUsuario.setClave(new String(getJpf_confirmarPassword().getPassword()));

        String password1 = String.valueOf(jpf_password.getPassword());
        String password2 = String.valueOf(jpf_confirmarPassword.getPassword());

        if ((!this.jtf_nickname.getText().isEmpty()) && !password1.isEmpty() && !password2.isEmpty() && password1.equals(password2)) {

            nuevoUsuario = new Usuario();
            nuevoUsuario.setNombre(this.jtf_nickname.getText());
            nuevoUsuario.setClave(password1);

            this.jlbl_alertaNickName.setIcon(null);
            this.jlbl_alertaPassword.setIcon(null);
            this.jlbl_alertaConfirmarPassword.setIcon(null);
            this.jlbl_alertaPersonaAsociada.setIcon(null);
            this.jlbl_alertaEmpleadoAsociado.setIcon(null);
            this.jlbl_mensaje.setText("");

        } else {
            if (this.jtf_nickname.getText().isEmpty()) {
                this.jlbl_alertaNickName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Nombre ";
            } else {
                this.jlbl_alertaNickName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (password1.isEmpty()) {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *password vacio ";
            } else {
                this.jlbl_alertaPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (password2.isEmpty()) {
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Confirmación de password vacio ";
            } else {
                this.jlbl_alertaConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            this.jlbl_mensaje.setText(mensaje);

        }
        if (nuevoUsuario != null) {
            if (this.controlador.modificarUsuario(usuarioSeleccionado, nuevoUsuario)) {

                this.jlbl_mensaje.setText("");

                //limpiar campos
                //Actualizar el TableModel con la lista del controlador
                this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

                //Refrescar el modelo en la tabla
                this.tablaUsuarioModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

                this.jtb_usuario.setEnabled(true);

                this.jtb_usuario.getSelectionModel().setSelectionInterval(this.tablaUsuarioModelo.buscarFilaUsuario(usuarioSeleccionado) - 1, this.tablaUsuarioModelo.buscarFilaUsuario(usuarioSeleccionado) - 1);

                seleccionarUsuario();

                int selectedRow = jtb_usuario.getSelectedRow();
                Rectangle rect = jtb_usuario.getCellRect(selectedRow, 0, true);
                jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
                crud = "";
            } else {
                this.jlbl_alertaPersonaAsociada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *El DNI ya existe, ingrese otro";
                this.jlbl_mensaje.setText(mensaje);
            }

        }
    }

    /**
     * Elimina una persona existente
     *
     * @throws java.sql.SQLIntegrityConstraintViolationException
     */
    public void eliminar() throws SQLIntegrityConstraintViolationException, SQLException {

        try {
            controlador.eliminarUsuario(usuarioSeleccionado);
            this.jlbl_mensaje.setText("");

            //limpiar campos
            //Actualizar el TableModel con la lista del controlador
            this.tablaUsuarioModelo.setUsuarios(this.controlador.buscarTodosLosUsuarios());

            //Refrescar el modelo en la tabla
            this.tablaUsuarioModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarUsuario);

            this.jtb_usuario.setEnabled(true);

            this.usuarioSeleccionado = null;

            this.jtb_usuario.getSelectionModel().setSelectionInterval(this.tablaUsuarioModelo.getRowCount() - 1, this.tablaUsuarioModelo.getRowCount() - 1);
            this.tablaUsuarioModelo.getValueAt(this.tablaUsuarioModelo.getRowCount() - 1, 0);

            seleccionarUsuario();

            int selectedRow = jtb_usuario.getSelectedRow();
            Rectangle rect = jtb_usuario.getCellRect(selectedRow, 0, true);
            jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
            crud = "";
        } catch (NonexistentEntityException ex) {
            //agregar mensaje que la persona esta asociada
            JOptionPane.showConfirmDialog(null, "Posee registros asociados", "Error Eliminación", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE);

            //Logger.getLogger(PanelPersona.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
