/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.OrganismoController;
import java.awt.Color;
import model.Organismo;

/**
 *
 * @author Ariel
 */
public class PanelOrganismo extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;
    
    private final OrganismoController controlador;
    private final Organismo organismoAuxiliar;

    /**
     * Creates new form PanelEmpresa
     */
    public PanelOrganismo() {
        initComponents();
        validador = new ValidadorDeCampos();
        habilitarTodosLosBotones(true);
        this.controlador = new OrganismoController();
        this.organismoAuxiliar = controlador.getOrganismoInstanciaUnica();
        
        this.jtf_razonSocial.setText(organismoAuxiliar.getNombre());
        this.jtf_direccion.setText(organismoAuxiliar.getDireccion());
        this.jtf_telefono.setText(organismoAuxiliar.getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jbtn_volver = new javax.swing.JButton();
        jtf_razonSocial = new javax.swing.JTextField();
        jtf_direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_telefono = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Razon Social:");
        add(jLabel2);
        jLabel2.setBounds(70, 50, 170, 30);

        jbtn_volver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_volver.setText("VOLVER");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });
        add(jbtn_volver);
        jbtn_volver.setBounds(70, 653, 720, 60);

        jtf_razonSocial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtf_razonSocial.setEnabled(false);
        jtf_razonSocial.setFocusable(false);
        add(jtf_razonSocial);
        jtf_razonSocial.setBounds(260, 50, 530, 30);

        jtf_direccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtf_direccion.setEnabled(false);
        jtf_direccion.setFocusable(false);
        add(jtf_direccion);
        jtf_direccion.setBounds(260, 120, 530, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Dirección:");
        add(jLabel3);
        jLabel3.setBounds(70, 120, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Teléfono:");
        add(jLabel4);
        jLabel4.setBounds(70, 190, 170, 30);

        jtf_telefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtf_telefono.setEnabled(false);
        jtf_telefono.setFocusable(false);
        add(jtf_telefono);
        jtf_telefono.setBounds(260, 190, 530, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();
        
        //Habilita el Arbol de seleccion
        JFramePrincipal.habilitarArbol(true);
    }//GEN-LAST:event_jbtn_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JTextField jtf_direccion;
    private javax.swing.JTextField jtf_razonSocial;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        //inhabilita campos
    }

    @Override
    public void limpiarTodosLosCampos() {
        this.validador.limpiarCampo(jtf_razonSocial);
        this.validador.limpiarCampo(jtf_direccion);
        this.validador.limpiarCampo(jtf_telefono);
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(estado, jbtn_volver, Color.red, Color.WHITE, null, null);
    }

}
