/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import javax.swing.tree.TreePath;
import static view.JFramePrincipal.jPanelContenido;

/**
 *
 * @author Ariel
 */
public class PanelArbolAdministrador extends javax.swing.JPanel {

    /**
     * captura la seleccion en el arbol
     */
    String captura = null;

    public PanelArbolAdministrador() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        panelContenedorArbol = new javax.swing.JPanel();
        arbolModulos = new javax.swing.JTree();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(350, 750));
        setMinimumSize(new java.awt.Dimension(350, 750));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 750));
        setLayout(null);

        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);
        jScrollPaneArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        panelContenedorArbol.setAlignmentX(0.0F);
        panelContenedorArbol.setAlignmentY(0.0F);
        panelContenedorArbol.setAutoscrolls(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("El Porvenir");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administración General");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Organismo");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestión de Turnos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Asignar Turno");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Reasignar Turno");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestion de Tramite");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Procesar Tramite");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver cantidad de Tramites por Area");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver cantidad deTipo de tramite por Area");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setMinimumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(300, 800));
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorArbolLayout = new javax.swing.GroupLayout(panelContenedorArbol);
        panelContenedorArbol.setLayout(panelContenedorArbolLayout);
        panelContenedorArbolLayout.setHorizontalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelContenedorArbolLayout.setVerticalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jScrollPaneArbol.setViewportView(panelContenedorArbol);

        add(jScrollPaneArbol);
        jScrollPaneArbol.setBounds(0, 0, 350, 750);
    }// </editor-fold>//GEN-END:initComponents


    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked

        if (arbolModulos.isEnabled()) {
            TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
            if (tp != null) {
                captura = arbolModulos.getSelectionPath().toString();
                /*Intentanmos validar si la cadena equivale a vacio.
              Si ejecutamos nos daremos cuenta que esto
             genera una excepciòn ya que la cadena es nula*/

                if (captura.equals("[El Porvenir, Administración General, Organismo]")) {
                    //Se crea el Panel Emplesa    
                    PanelOrganismo unPanelEmpresa = new PanelOrganismo();
                    unPanelEmpresa.setSize(950, 750);
                    unPanelEmpresa.setLocation(0, 0);
                    unPanelEmpresa.setVisible(true);

                    jPanelContenido.removeAll();
                    jPanelContenido.add(unPanelEmpresa, BorderLayout.NORTH);
                    jPanelContenido.repaint();

                    habilitarArbol(false);
                }

                if (captura.equals("[El Porvenir, Administración General, Personas]")) {

                    //Se crea el Panel Emplesa    
                    PanelPersona unPanelPersona = new PanelPersona();
                    unPanelPersona.setSize(950, 750);
                    unPanelPersona.setLocation(0, 0);
                    unPanelPersona.setVisible(true);

                    //Elimina Panel Anterior
                    jPanelContenido.removeAll();
                    //Agrega Panel Nuevo Panel Persona
                    jPanelContenido.add(unPanelPersona, BorderLayout.NORTH);
                    //Repinta Nuevo Panel
                    jPanelContenido.repaint();

                    //Arbol Inhabilitado
                    habilitarArbol(false);
                }
                if (captura.equals("[El Porvenir, Administración General, Empleados]")) {

                    //Se crea el Panel Emplesa    
                    PanelEmpleado unPanelEmpleado = new PanelEmpleado();
                    unPanelEmpleado.setSize(950, 750);
                    unPanelEmpleado.setLocation(0, 0);
                    unPanelEmpleado.setVisible(true);

                    //Elimina Panel Anterior
                    jPanelContenido.removeAll();
                    //Agrega Panel Nuevo Panel Persona
                    jPanelContenido.add(unPanelEmpleado, BorderLayout.NORTH);
                    //Repinta Nuevo Panel
                    jPanelContenido.repaint();

                    //Arbol Inhabilitado
                    habilitarArbol(false);
                }
                
                if (captura.equals("[El Porvenir, Administración General, Usuarios]")) {

                    //Se crea el Panel Emplesa    
                    PanelUsuario unPanelUsuario = new PanelUsuario();
                    unPanelUsuario.setSize(950, 750);
                    unPanelUsuario.setLocation(0, 0);
                    unPanelUsuario.setVisible(true);

                    //Elimina Panel Anterior
                    jPanelContenido.removeAll();
                    //Agrega Panel Nuevo Panel Persona
                    jPanelContenido.add(unPanelUsuario, BorderLayout.NORTH);
                    //Repinta Nuevo Panel
                    jPanelContenido.repaint();

                    //Arbol Inhabilitado
                    habilitarArbol(false);
                }
            }
        }

    }//GEN-LAST:event_arbolModulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolModulos;
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JPanel panelContenedorArbol;
    // End of variables declaration//GEN-END:variables

    /**
     * Habilita o deshabilita el arbol
     *
     * @param estado
     */
    public void habilitarArbol(boolean estado) {
        if (estado) {
            arbolModulos.setEnabled(true);
        } else {
            arbolModulos.setEnabled(false);
        }
    }
}
